#!/usr/bin/env bash
set -eo pipefail

# Fix the shared raw-image dataset so AP02/AP03 use the real AP01 moving-camera sequence,
# while keeping the existing AP01 pipeline/results untouched.
#
# Run from anywhere; it will cd to /workspaces/project if available.
#
# What this script does:
#   1. Uses AP01's real moving sequence as the canonical shared moving raw images.
#   2. Keeps/copies static snapshots and camera_info into the shared raw dataset.
#   3. Re-runs AP02 detection/debug from the shared raw dataset.
#   4. Writes manifests so it is clear where every raw input came from.
#
# What this script does NOT do:
#   - It does not edit AP01 scripts.
#   - It does not delete or overwrite AP01 result folders.
#   - It does not re-run AP01.
#   - It does not capture new images from Gazebo.

PROJECT_ROOT="/workspaces/project"
if [ -d "$PROJECT_ROOT" ]; then
  cd "$PROJECT_ROOT"
fi

RAW="results/bus_real_data/00_raw_images/bus_real_data_ref_marker_v1"
AP1_ROOT="results/bus_real_data/01_marker_direct_relay_multimarker_multichain"
AP1_MOVING="$AP1_ROOT/03_moving_camera_sequence/images"
AP2_ROOT="results/bus_real_data/02_ref_marker_graph_ba"

echo "=== Check source paths ==="
if [ ! -d "$AP1_MOVING" ]; then
  echo "[ERROR] AP01 moving image sequence not found:"
  echo "        $AP1_MOVING"
  echo
  echo "Expected the real moving sequence generated by AP01, e.g. frame_0000.png, frame_0001.png, ..."
  exit 1
fi

AP1_MOVING_COUNT=$(find "$AP1_MOVING" -maxdepth 1 -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' \) | wc -l)
if [ "$AP1_MOVING_COUNT" -lt 10 ]; then
  echo "[ERROR] AP01 moving image sequence has too few images: $AP1_MOVING_COUNT"
  exit 1
fi

echo "[OK] AP01 moving sequence: $AP1_MOVING"
echo "[OK] AP01 moving images: $AP1_MOVING_COUNT"

mkdir -p "$RAW/static" "$RAW/moving" "$RAW/camera_info"

echo
echo "=== Replace shared raw moving sequence with AP01 real moving sequence ==="
rm -rf "$RAW/moving"
mkdir -p "$RAW/moving"
rsync -av --delete "$AP1_MOVING/" "$RAW/moving/"

RAW_MOVING_COUNT=$(find "$RAW/moving" -maxdepth 1 -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' \) | wc -l)
echo "[OK] shared raw moving images now: $RAW_MOVING_COUNT"

echo
echo "=== Ensure shared static snapshots exist ==="
# Prefer already existing shared static snapshots; if missing, try common AP01 static locations.
STATIC_COUNT=$(find "$RAW/static" -maxdepth 1 -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' \) 2>/dev/null | wc -l || true)

if [ "$STATIC_COUNT" -lt 4 ]; then
  echo "[WARN] shared static snapshots missing/incomplete. Trying to recover from common AP01 locations..."

  # Candidate folders. Keep this broad because AP01 debug/raw image folder names may differ between runs.
  CANDIDATES=(
    "$AP1_ROOT/01_static_a4_marker_detection/raw_images"
    "$AP1_ROOT/01_static_a4_marker_detection/images"
    "$AP1_ROOT/01_static_a4_marker_detection/static_images"
    "$AP1_ROOT/01_static_a4_marker_detection/debug_images"
    "$AP1_ROOT/01_static_a4_marker_detection"
  )

  for CAM in cam_edge_0 cam_edge_1 cam_edge_3 cam_edge_5; do
    if [ -f "$RAW/static/${CAM}.png" ]; then
      continue
    fi

    FOUND=""
    for DIR in "${CANDIDATES[@]}"; do
      [ -d "$DIR" ] || continue

      for PAT in \
        "${CAM}.png" \
        "${CAM}_raw.png" \
        "${CAM}_image.png" \
        "${CAM}_detections.png" \
        "*${CAM}*.png"
      do
        CANDIDATE=$(find "$DIR" -maxdepth 1 -type f -name "$PAT" | head -n 1 || true)
        if [ -n "$CANDIDATE" ]; then
          FOUND="$CANDIDATE"
          break
        fi
      done

      [ -n "$FOUND" ] && break
    done

    if [ -n "$FOUND" ]; then
      cp "$FOUND" "$RAW/static/${CAM}.png"
      echo "[OK] recovered static ${CAM}: $FOUND"
    else
      echo "[WARN] could not recover static snapshot for ${CAM}"
    fi
  done
fi

STATIC_COUNT=$(find "$RAW/static" -maxdepth 1 -type f \( -name '*.png' -o -name '*.jpg' -o -name '*.jpeg' \) 2>/dev/null | wc -l || true)
echo "[OK] shared static snapshots: $STATIC_COUNT"

if [ "$STATIC_COUNT" -lt 4 ]; then
  echo "[ERROR] shared static snapshots still incomplete."
  echo "        Need cam_edge_0.png, cam_edge_1.png, cam_edge_3.png, cam_edge_5.png in:"
  echo "        $RAW/static"
  exit 1
fi

echo
echo "=== Ensure camera_info exists ==="
INFO_COUNT=$(find "$RAW/camera_info" -maxdepth 1 -type f -name '*.json' 2>/dev/null | wc -l || true)
echo "[OK] shared camera_info json files: $INFO_COUNT"

if [ "$INFO_COUNT" -lt 5 ]; then
  echo "[WARN] camera_info JSON files are incomplete. AP02 detection may fail unless these files exist:"
  echo "       $RAW/camera_info/cam_edge_0.json"
  echo "       $RAW/camera_info/cam_edge_1.json"
  echo "       $RAW/camera_info/cam_edge_3.json"
  echo "       $RAW/camera_info/cam_edge_5.json"
  echo "       $RAW/camera_info/moving_calib_camera.json"
fi

echo
echo "=== Write shared raw dataset manifest ==="
cat > "$RAW/MANIFEST.txt" <<EOF
Dataset: bus_real_data_ref_marker_v1
Purpose: Shared raw-image dataset for AP02 graph BA and AP03 targetless COLMAP + ArUco scale.
Scene: bus_real_data_moving_camera

Canonical source:
- moving/: copied from AP01 real moving sequence:
  $AP1_MOVING
- static/: static snapshots for cam_edge_0, cam_edge_1, cam_edge_3, cam_edge_5
- camera_info/: ROS camera_info JSON files

Counts at manifest creation:
- moving images: $RAW_MOVING_COUNT
- static images: $STATIC_COUNT
- camera_info json files: $INFO_COUNT

Important contract:
- This folder contains raw input images only.
- Approach-specific detections/results must be written into their own result folders.
- AP01 is not modified by this fix.
- AP02 and AP03 should read raw images from this folder instead of using approach-internal raw image folders.
- Do not overwrite this dataset unless intentionally creating a new dataset version.
EOF

mkdir -p "results/bus_real_data/00_raw_images"
cat > "results/bus_real_data/00_raw_images/README.md" <<'EOF'
# Shared raw image datasets

This folder stores approach-independent raw image datasets.

Current canonical dataset:

```text
results/bus_real_data/00_raw_images/bus_real_data_ref_marker_v1/
```

Contract:

- Raw images and camera_info only.
- No approach-specific detections.
- No approach-specific estimates.
- AP02/AP03 should read from this folder.
- Each approach writes its own detections/results into its own result folder.
- AP01 remains untouched as the frozen baseline; its real moving sequence is used as the canonical moving raw sequence for this dataset.
EOF

echo
echo "=== Remove stale AP02-internal raw image dataset if present ==="
if [ -d "$AP2_ROOT/01_dataset" ]; then
  rm -rf "$AP2_ROOT/01_dataset"
  echo "[OK] removed stale $AP2_ROOT/01_dataset"
else
  echo "[OK] no stale $AP2_ROOT/01_dataset present"
fi

echo
echo "=== Patch AP02 detection defaults if files exist ==="
DETECT="run/bus_real_data/approach2_ref_marker_graph_ba/02_detect_ap02_aruco_observations.py"
if [ -f "$DETECT" ]; then
  python3 - <<'PY'
from pathlib import Path
p = Path("run/bus_real_data/approach2_ref_marker_graph_ba/02_detect_ap02_aruco_observations.py")
s = p.read_text()
s = s.replace('ap.add_argument("--dataset", default=str(AP02_ROOT / "01_dataset"))',
              'ap.add_argument("--dataset", default="results/bus_real_data/00_raw_images/bus_real_data_ref_marker_v1")')
# In case it was already partially patched differently, keep as-is.
p.write_text(s)
print("[OK] patched", p)
PY
else
  echo "[WARN] AP02 detection script not found: $DETECT"
fi

echo
echo "=== Patch/create AP02 offline detect/debug runner ==="
RUNNER="run/bus_real_data/approach2_ref_marker_graph_ba/run_approach2_phase1_detect_debug.sh"
mkdir -p "$(dirname "$RUNNER")"
cat > "$RUNNER" <<'SH'
#!/usr/bin/env bash
set -eo pipefail

cd /workspaces/project

echo "=== AP02 Phase 1: detect AP02 ArUco observations from shared raw dataset ==="
python3 run/bus_real_data/approach2_ref_marker_graph_ba/02_detect_ap02_aruco_observations.py \
  --dataset results/bus_real_data/00_raw_images/bus_real_data_ref_marker_v1

echo
echo "=== AP02 Phase 1: make debug artifacts ==="
python3 run/bus_real_data/approach2_ref_marker_graph_ba/03_make_ap02_debug_artifacts.py

echo
echo "=== AP02 Detection Summary ==="
cat results/bus_real_data/02_ref_marker_graph_ba/02_aruco_observations/ap02_detection_summary.txt

echo
echo "=== AP02 Debug Report ==="
cat results/bus_real_data/02_ref_marker_graph_ba/03_debug_artifacts/ap02_debug_artifacts_report.txt

echo
echo "[OK] AP02 Phase 1 detect/debug complete."
SH
chmod +x "$RUNNER"
echo "[OK] wrote $RUNNER"

echo
echo "=== Clean stale AP02 detection/debug outputs and regenerate from corrected shared raw dataset ==="
rm -rf "$AP2_ROOT/02_aruco_observations"
rm -rf "$AP2_ROOT/03_debug_artifacts"

bash "$RUNNER"

echo
echo "=== Sanity: AP02 must not reference AP01 results directly ==="
if grep -R "01_marker_direct_relay\|AP1_ROOT\|AP01_ROOT\|moving_detections.csv\|01_static_a4_marker_detection" -n run/bus_real_data/approach2_ref_marker_graph_ba; then
  echo "[ERROR] AP02 scripts still reference AP01 result internals. Fix before continuing."
  exit 1
fi
echo "[OK] AP02 scripts do not reference AP01 internals."

echo
echo "=== Final status ==="
echo "[OK] Shared raw moving sequence now comes from AP01 real moving images."
echo "[OK] AP01 pipeline/results were not modified."
echo "[OK] AP02 detections/debug were regenerated from shared raw dataset."
echo
echo "Next recommended command:"
echo "  bash run/bus_real_data/approach2_ref_marker_graph_ba/run_approach2_phase2_graph_init.sh"
